apiVersion: v1
kind: Service
metadata:
  name: aivid-cloud-mqtt-service
  namespace: {{ .Values.global.namespace }}
  labels:
    app: aivid-cloud-mqtt
    app.kubernetes.io/name: mqtt
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
    app.kubernetes.io/managed-by: helm
spec:
  type: {{ .Values.service.type }}
  ports:
  - port: {{ .Values.service.port }}
  selector:
    app: aivid-cloud-mqtt
