apiVersion: v1
kind: Service
metadata:
  name: aivid-cloud-master-node-api-service
  namespace: default
  labels:
    app: aivid-cloud-master-node-api
spec:
  ports:
  - port: 4004
    protocol: TCP
  selector:
    app: aivid-cloud-master-node-api